### ISSUE TITLE
Bug Report: xloil.ErrorCode.NA Displays Incorrectly When Assigned Directly to Chart Data

### ISSUE THREAD

**Issue by gnyuan** [cunnane/xloil#105]
I encountered a bug related to the handling of xloil.ErrorCode.NA when assigning it directly to chart data. The issue manifests as follows:

When xloil.ErrorCode.NA is assigned directly to chart data, the displayed value in the chart is the enum value 42, instead of showing #N/A as expected. However, if xloil.ErrorCode.NA is assigned to a cell, and the chart references data from this cell, the result is correctly displayed as #N/A.

```python
import numpy as np
import xloil as xlo

@xlo.func(command=True)
def add_chart():
    ws = xlo.active_worksheet()
    chart1 = ws.Shapes.AddChart2().Chart
    chart1.ChartTitle.Text = 'Not Expected. the second value is 42'
    chart1.SeriesCollection().NewSeries()
    chart1.SeriesCollection(1).Values = [1 ,xlo.CellError.NA, 3]

    chart2 = ws.Shapes.AddChart2().Chart
    chart2.ChartTitle.Text = 'Expected.'
    ws.Shapes(2).Left = 0
    chart2.SeriesCollection().NewSeries()
    ws.range(0,0,0,2).value = np.array([[1, xlo.CellError.NA, 3]])
    chart2.SeriesCollection(1).Values = ws.range(0,0,0,2)
```
![image](https://github.com/cunnane/xloil/assets/6140657/8383014e-93b5-41fa-ba9d-c3bed3d2e733)

Thanks!

**Comment by gnyuan** [comment]
Hi cunnane,
Thanks for your help!

I tried changing the value from `xlo.CellError.NA` to `win32com.client.constants.xlErrNA`, but it's still not working as expected. Excel seems to be interpreting xlErrNA as a regular number instead of a #N/A error.
I suspect this might be caused by the cell formatting. There is something relate to format the cell correctly to display #N/A when using xlErrNA

Although formatting could be the issue, in my case, it's not a major problem to populate the data range first and then have the chart refer to that range. Thanks again for your insights!

```python
from win32com.client import constants
@xlo.func(command=True)
def add_chart():
    ws = xlo.active_worksheet()
    chart1 = ws.Shapes.AddChart2().Chart
    chart1.ChartTitle.Text = 'Not Expected. the second value is 42'
    chart1.SeriesCollection().NewSeries()
    chart1.SeriesCollection(1).Values = [1 ,constants.xlErrNA, 3]
```

![excel截图20240620132516](https://github.com/cunnane/xloil/assets/6140657/bcf8a30b-c98e-411c-ba3e-0ece407b3356)

**Comment by cunnane** [comment]
After some experimentation I discovered: pass `pythoncom.Empty` to get the expected behaviour

**Comment by gnyuan** [comment]
Thank you for sharing this nifty trick; it's very useful!! However, in my actual project, I still prefer to assign the values first and then create the chart. This approach helps to avoid any potential issues later on.
