### ISSUE TITLE
numpy dependency pinning following 2.0.0 release

### ISSUE THREAD

**Issue by andyvandy** [cunnane/xloil#108]
Numpy 2 was just released so we should specify the dependency to be on version `1.x.y` until numpy 2 is supported. 

https://github.com/cunnane/xloil/blob/39ec5ac93cbfacab9b2da25e3c1ce65551d9b1a5/libs/xlOil_Python/Package/setup.py#L96

https://github.com/numpy/numpy/releases/tag/v2.0.0

( I was using 0.18.6/0.18.5 so apologies if I missed uplifts that resolve this! )

**Comment by cunnane** [comment]
Thanks, good spot. It was actually straightforward to upgrade to support numpy 2, so I'll release a new version with this

**Comment by andyvandy** [comment]
Amazing, much appreciated!

**Comment by cunnane** [comment]
This is done in 0.19.0 which I just released
