### ISSUE TITLE
question about Python 3.12

### ISSUE THREAD

**Issue by dutch-rob** [cunnane/xloil#110]
When I try to use my xloil code with Python 3.12, it fails and when I switch back to 3.11 it works.
That made me wonder: Does xloil work with 3.12?
I see in the release history on gitlab that version 18.0 has Python 3.12 support but PyPi lists python versions up to 3.11.

BTW:
The xloil ribbon in Excel gives a dropdown for "Environment" which offers on my PC: Python 3.11 and Python 3.12.
Though I installed xloil for 3.11, the dropdown defaults to 3.12. When I select 3.11 instead, it still defaults to 3.12 when I open Excel again. 
I tried changing the .ini file to: XLOIL_PYTHON_VERSION="3.11" but also then Excel open with default set to 3.12. When I select 3.11, the .ini gets updated automatically but it changes to: XLOIL_PYTHON_VERSION="" and, of course, also then when starting Excel again, it defaults to 3.12.
I have the impression that that defaulting to... doesn't matter much because xloil appears to use 3.11 anyway, I assume based on the .ini line PYTHONEXECUTABLE=... .
However, I recently got my PC reimaged, therefore I was reinstalling a lot, and then this default gave me the impression that I was working with 3.12, which led to some confusion for me.
I would like it if the "Environment" dropdown doesn't appear if it doesn't affect anything, or that it defaults to the version in use. But please don't bother changing if you think it would probably be just for me.

**Comment by cunnane** [comment]
xlOil does work with python 3.12, however there's an excel crashing bug in the COM bit which only seems to trigger with 3.12.  Will let you know when I do a release and fix this

**Comment by dutch-rob** [comment]
Oh I see. 
Thanks for the update!!

**Comment by dutch-rob** [comment]
Great, thanks!!
