### ISSUE TITLE
Excel 365 crashers after 1st UDF call

### ISSUE THREAD

**Issue by rizzato** [cunnane/xloil#15]
Hi,

I'm trying it with Excel 365 MSO (16.0.14326.21116) 64-bit and Python 3.7.4.

Create the file MyTest.py with:
```
import xloil as xlo

@xlo.func
def Greetings(who):
    return f'Hello {who}!'
```
and saved a MyTest.xlsm in the same folder.

After calling `=Greetings("anything")` excel breaks, without leaving any relevant log in file. 

Could you help me understand what's going on?

Thanks a lot

**Comment by cunnane** [comment]
Sorry, xlOil v0.15 is broken for Python 3.6 & 3.7!  I've fixed this in v0.15.2 - just redownload from PyPI
