### ISSUE TITLE
Python only in current user

### ISSUE THREAD

**Issue by Borrdom** [cunnane/xloil#16]
Hi Steven,

thank you so much for this excellent package. I had speed issues with xlwings which are now history. xloil is truly a hidden gem in this regard. 

Now to the issue:
I ran into a minor issue when running xloil on environments where python was installed only for the current user.

more precisly a directory corresponding to something like this: 
%USERPROFILE%\AppData\Local\Programs\python\python39

Then the registry key for Software\Python only exist in HKEY_CURRENT_USER and not on HKEY_LOCAL_MACHINE

As a result, the xloil.log reports an error on
xloil_ribbon.py on line 144:
with reg.OpenKey(reg.HKEY_LOCAL_MACHINE, "Software\\Python") as kPythons:

As a quick-fix, i just replaced it: 
with reg.OpenKey(reg.HKEY_CURRENT_USER, "Software\\Python") as kPythons:
and it worked. It might be the easiest to just include both locations?

Thanks in advance
Dominik

**Comment by cunnane** [comment]
Glad you are enjoying xlOil!  It is definitely optimised for speed (at the cost of risking a crash of Excel) and something like capturing an array input to a function happens entirely in C++, so it performs similarly to something like ExcelDNA until you add some python loops!

These are the kind of issue reports I like - with an included fix :)  Your suggest makes perfect sense, I'll pull in the contents of both locations (if they exist) and put this in the next release

**Comment by cunnane** [comment]
I've put a fix for this in v0.15.4 which is available now.

**Comment by Borrdom** [comment]
Hi Steven,

I tested it on different PCs and it works :). Wonderful, thank you. I am closing this now.

Best Regards 

Dominik
