### ISSUE TITLE
Excel crashes on close with xlOil 0.15.2

### ISSUE THREAD

**Issue by hreddy-arb** [cunnane/xloil#18]
Hi Steven,

This is a great project and very much needed for the Excel community. I was using xlWings before this and have seen amazing performance improvement with xlOil.

The latest version 0.15.2 seems to be crashing Excel when I close it. It works fine until then (when Excel is open).
My python version is 3.8.10.

If I remove xloil from XLSTART folder, Excel does not crash anymore.
If i downgrade xloil to 0.12.0, Excel does not crash anymore.

Please let me know if I can provide any additional information to help debug this.

Thanks and Regards,
Harish

**Comment by cunnane** [comment]
Let me see if I can reproduce, does it happen always or only when you make use of xloil in some way?  If you could send a log with the log level at debug and the flush level also at debug ( in the xloil.ini file) that may give some clues.  I'm going to be away a few days so can't get to this immediately.

**Comment by sthlove** [comment]
if you don't need "xlOil_SQL", "xlOil_Utils"。
The xlOil.ini configuration table is modified like this
#Plugins=["xlOil_Python", "xlOil_SQL", "xlOil_Utils"]
Plugins=["xlOil_Python"]
It's not easy to crash

**Comment by cunnane** [comment]
@sthlove have you observed fewer (or ideally no) crashes when the SQL and Utils plugins are disabled?  I'm suprised since those plugins don't have much static state.

**Comment by cunnane** [comment]
Closing this as inactive - hope it's now working with 0.17.6
