### ISSUE TITLE
Udf add-in error on 0.17.1.

### ISSUE THREAD

**Issue by mskz1** [cunnane/xloil#32]
Hi,

My UDF add-in works fine on 0.16.4, but I update to 0.17.1 got some error at registering udf functions.

Please refer the log file.
[log_2023-0209.txt](https://github.com/cunnane/xloil/files/10694454/log_2023-0209.txt)

Thanks in advance.

windows10
python3.8.10(WinPython)
xlOil 0.17.1

**Comment by cunnane** [comment]
Ah, this is due to some internal diffs in the typing module between 3.8 and 3.9.  I'll fix but in the meantime its safe to remove the 3 lines in `xloil\register.py` starting with line 67.

**Comment by cunnane** [comment]
This is fixed in 0.17.3 (now on PyPI)

**Comment by mskz1** [comment]
I updated to 0.17.3 and works fine.
Thank you so much!
