### ISSUE TITLE
Getting started ModuleNotFoundError

### ISSUE THREAD

**Issue by ShieldTrade** [cunnane/xloil#36]
Windows 10, python 3.9, Excel 2021, xloil 0.17.17

I have xloil correctly installed in my venv C:\ShieldTrade\Python_projects\venv\lib\site-packages\xloil\

It looks to me that xloil is trying to use the interpreter in C:\Users\lucio\AppData\Local\Programs\Python\Python39 while trying to import module while it should use C:\ShieldTrade\Python_projects\venv\scripts\python.exe ( same venv). 

looking at the sys.path=['C:\\ShieldTrade\\Python_projects', 'C:\\ShieldTrade\\Python_projects', ..... ] I think there is something conflicting with xloil setting as in yours [8](https://github.com/cunnane/xloil/issues/8)

> If you have any python directories in your system environment variables (not recommended) then this may well conflict with xlOil's settings.

```
Traceback (most recent call last):
  File "C:\ShieldTrade\Python_projects\venv\lib\site-packages\xloil\_core.py", line 61, in <module>
    mod = importlib.import_module(pyd_name)
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'xlOil_Python39'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ShieldTrade\Python_projects\_MULTY_BOTS.py", line 27, in <module>
    import xloil as xlo   #   se run non posso importare oil
  File "C:\ShieldTrade\Python_projects\venv\lib\site-packages\xloil\__init__.py", line 2, in <module>
    from ._core import *
  File "C:\ShieldTrade\Python_projects\venv\lib\site-packages\xloil\_core.py", line 63, in <module>
    raise ModuleNotFoundError(f"Failed to load {pyd_name} with " +
ModuleNotFoundError: Failed to load xlOil_Python39 with sys.path=['C:\\ShieldTrade\\Python_projects', 'C:\\ShieldTrade\\Python_projects', 'C:\\Users\\lucio\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip', 'C:\\Users\\lucio\\AppData\\Local\\Programs\\Python\\Python39\\DLLs', 'C:\\Users\\lucio\\AppData\\Local\\Programs\\Python\\Python39\\lib', 'C:\\Users\\lucio\\AppData\\Local\\Programs\\Python\\Python39', 'C:\\ShieldTrade\\Python_projects\\venv', 'C:\\ShieldTrade\\Python_projects\\venv\\lib\\site-packages', 'C:\\ShieldTrade\\Python_projects\\venv\\share\\xloil'] and PATH=C:\ShieldTrade\Ave\venv\Scripts;C:\Users\lucio\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\lucio\AppData\Local\Programs\Python\Python39\;C:\Program Files\Python39\Scripts\;C:\Program Files\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Users\lucio\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\lucio\AppData\Local\Microsoft\WindowsApps;C:\Users\lucio\AppData\Roaming\npm;C:\Program Files\OpenSSL-Win64\bin
```

**Comment by cunnane** [comment]
To load  venv correctly, you should have `PYTHONEXECUTABLE` in your xloil.ini pointing at the *python.exe* in your venv.  You also need `XLOIL_PATH` to point to the xlOil DLLs, ideally in the same venv, but any location containing matching version DLLs will do.

You shouldn't need to set anything else on your `PATH` or `PYTHONPATH`.

From the error it looks like various pythons have found their way into your `PATH`, you're referencing
  * C:\ShieldTrade\Ave\venv\Scripts;
  * C:\Users\lucio\AppData\Local\Programs\Python\Python39\Scripts;
  * C:\Users\lucio\AppData\Local\Programs\Python\Python39\;
  * C:\Program Files\Python39\Scripts\;
  * C:\Program Files\Python39\

In your `PYTHONPATH` or  `sys.path`,  you have both: 
  * C:\Users\lucio\AppData\Local\Programs\Python\Python39
  * C:\ShieldTrade\Python_projects\venv

Can you check your `%APPDATA%\xlOil\xlOil.ini` and your Windows environment variables `PATH` and `PYTHONPATH` for instances of pythons?

**Comment by ShieldTrade** [comment]
I admit I am not really understanding what is going on. It s due to my lack of skill regarding installations/ venv . 
I am sorry :-)

> Can you check your %APPDATA%\xlOil\xlOil.ini

in C:\Users\lucio\AppData\Roaming\xlOil
I found  the attached file. not sure if that is what you need.
[config_setting.txt](https://github.com/cunnane/xloil/files/11310398/config_setting.txt)

> Windows environment variables PATH and PYTHONPATH

see image. As far as I understand Path does not have

![Screenshot 2023-04-24 110210](https://user-images.githubusercontent.com/62026612/233996953-e7f9dc80-9969-45a0-9448-7496c79fc5e3.png)

**Comment by cunnane** [comment]
I'd advise taking any reference to 'python' out of your system PATH as this can interfere with virtual envs.  If you want to be able to easily run `python myscript.py` at the command prompt, in window you can type `py myscript.py` which doesn't have the requirement for `python.exe` to be on the path (assuming you've used the standard python installer).

**Comment by cunnane** [comment]
You can see it's trying to load python 3.8.  The way xlOil determines the version is by loading `python.dll` and asking it which version it is.  This suggests somehow on your path is a python.dll with the wrong version.  You can override this by setting `XLOIL_PYTHON_VERSION` to 3.9 in your ini file.

Also, somehow you still have another python on the path: `C:\Users\lucio\AppData\Local\Programs\Python\Python39`.  Is this the python version from which you created the venv?

**Comment by ShieldTrade** [comment]
Thankyou @cunnane.. 
I am now lost :-)

> You can override this by setting XLOIL_PYTHON_VERSION to 3.9 in your ini file.

please explain a little bit more. when you say

> ini file.

you mean the TOM file in C:\Users\lucio\AppData\Roaming\xlOil?

> C:\Users\lucio\App

Data\Local\Programs\Python\Python39. Is this the python version from which you created the venv?

yes

if I run this code using the sam venv where xloil is installed

`pprint({
    'sys.version_info': sys.version_info,
    'sys.prefix': sys.prefix,
    'sys.path': sys.path,
    'PATH': os.environ['PATH'].split(os.pathsep),
    'Users Environment variable:': dict(os.environ),
})

I get
`
`{'PATH': ['C:\\ShieldTrade\\Ave\\venv\\Scripts',
          'C:\\Windows\\system32',
          'C:\\Windows',
          'C:\\Windows\\System32\\Wbem',
          'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\',
          'C:\\Windows\\System32\\OpenSSH\\',
          'C:\\Program Files\\Git\\cmd',
          'C:\\Program Files\\Amazon\\AWSCLIV2\\',
          'C:\\Program Files\\nodejs\\',
          'C:\\Program Files\\PuTTY\\',
          'C:\\Users\\lucio\\AppData\\Local\\Microsoft\\WindowsApps',
          'C:\\Users\\lucio\\AppData\\Roaming\\npm',
          'C:\\Program Files\\OpenSSL-Win64\\bin',
          ''],
 'Users Environment variable:': {'ALLUSERSPROFILE': 'C:\\ProgramData',
                                 'APPDATA': 'C:\\Users\\lucio\\AppData\\Roaming',
                                 'COMMONPROGRAMFILES': 'C:\\Program '
                                                       'Files\\Common Files',
                                 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files '
                                                            '(x86)\\Common '
                                                            'Files',
                                 'COMMONPROGRAMW6432': 'C:\\Program '
                                                       'Files\\Common Files',
                                 'COMPUTERNAME': 'DESKTOP-V19EA61',
                                 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe',
                                 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
                                 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet '
                                                                   'Explorer',
                                 'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
                                 'HOMEDRIVE': 'C:',
                                 'HOMEPATH': '\\Users\\lucio',
                                 'IDEA_INITIAL_DIRECTORY': 'C:\\Users\\lucio\\Desktop',
                                 'LOCALAPPDATA': 'C:\\Users\\lucio\\AppData\\Local',
                                 'LOGONSERVER': '\\\\DESKTOP-V19EA61',
                                 'NUMBER_OF_PROCESSORS': '4',
                                 'ONEDRIVE': 'C:\\Users\\lucio\\OneDrive',
                                 'OS': 'Windows_NT',
                                 'PATH': 'C:\\ShieldTrade\\Ave\\venv\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program '
                                         'Files\\Git\\cmd;C:\\Program '
                                         'Files\\Amazon\\AWSCLIV2\\;C:\\Program '
                                         'Files\\nodejs\\;C:\\Program '
                                         'Files\\PuTTY\\;C:\\Users\\lucio\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\lucio\\AppData\\Roaming\\npm;C:\\Program '
                                         'Files\\OpenSSL-Win64\\bin;',
                                 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
                                 'PROCESSOR_ARCHITECTURE': 'AMD64',
                                 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 '
                                                         'Model 26 Stepping 5, '
                                                         'GenuineIntel',
                                 'PROCESSOR_LEVEL': '6',
                                 'PROCESSOR_REVISION': '1a05',
                                 'PROGRAMDATA': 'C:\\ProgramData',
                                 'PROGRAMFILES': 'C:\\Program Files',
                                 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
                                 'PROGRAMW6432': 'C:\\Program Files',
                                 'PROMPT': '(venv) $P$G',
                                 'PSMODULEPATH': 'C:\\Program '
                                                 'Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
                                 'PUBLIC': 'C:\\Users\\Public',
                                 'PYCHARM_HOSTED': '1',
                                 'PYTHONIOENCODING': 'UTF-8',
                                 'PYTHONPATH': 'C:\\ShieldTrade\\Ave',
                                 'PYTHONUNBUFFERED': '1',
                                 'SESSIONNAME': 'Console',
                                 'SYSTEMDRIVE': 'C:',
                                 'SYSTEMROOT': 'C:\\Windows',
                                 'TEMP': 'C:\\Users\\lucio\\AppData\\Local\\Temp',
                                 'TMP': 'C:\\Users\\lucio\\AppData\\Local\\Temp',
                                 'USERDOMAIN': 'DESKTOP-V19EA61',
                                 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-V19EA61',
                                 'USERNAME': 'lucio',
                                 'USERPROFILE': 'C:\\Users\\lucio',
                                 'VIRTUAL_ENV': 'C:\\ShieldTrade\\Ave\\venv',
                                 'WINDIR': 'C:\\Windows',
                                 '_OLD_VIRTUAL_PATH': 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program '
                                                      'Files\\Git\\cmd;C:\\Program '
                                                      'Files\\Amazon\\AWSCLIV2\\;C:\\Program '
                                                      'Files\\nodejs\\;C:\\Program '
                                                      'Files\\PuTTY\\;C:\\Users\\lucio\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\lucio\\AppData\\Roaming\\npm;C:\\Program '
                                                      'Files\\OpenSSL-Win64\\bin;',
                                 '_OLD_VIRTUAL_PROMPT': '$P$G'},
 'sys.path': ['C:\\ShieldTrade\\Ave',
              'C:\\ShieldTrade\\Ave',
              'C:\\Users\\lucio\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',
              'C:\\Users\\lucio\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',
              'C:\\Users\\lucio\\AppData\\Local\\Programs\\Python\\Python39\\lib',
              'C:\\Users\\lucio\\AppData\\Local\\Programs\\Python\\Python39',
              'C:\\ShieldTrade\\Ave\\venv',
              'C:\\ShieldTrade\\Ave\\venv\\lib\\site-packages'],
 'sys.prefix': 'C:\\ShieldTrade\\Ave\\venv',
 'sys.version_info': sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)}`

![Screenshot 2023-04-26 151738](https://user-images.githubusercontent.com/62026612/234588081-4d91f713-13f3-4555-bb4f-c402a19ed6d9.png)
![Screenshot 2023-04-26 151828](https://user-images.githubusercontent.com/62026612/234588086-bf083c6a-eb41-4e3f-b8e5-92b3b6e2ba31.png)

**Comment by cunnane** [comment]
OK fantastic glad you have got it working!
