### ISSUE TITLE
Fail to Load Add-in with Python 3.11

### ISSUE THREAD

**Issue by stefanomorni** [cunnane/xloil#40]
I get the following error when opening excel with xloil pointing to a Python environment with python 3.11 installed:

Failed LoadLibrary for: xlOil_Python310.pyd

Does xloil work with python 3.11?
Do I have to revert to python 3.10?

Do you have any suggestion?

Many thanks for developing and sharing xloil :)

Best regards

Stefano

**Comment by stefanomorni** [comment]
Sorry. In the above post, I forgot to mention, that I'm running:

- Windows 10
- Microsoft® Excel® per Microsoft 365 MSO (Versione 2303 Build 16.0.16227.20202) a 64 bit 
- xlOil Version 0.17.8

Thanks

**Comment by cunnane** [comment]
When it loads, xlOil looks for `python3.dll` on your path and queries it as to the version of python to load.  It seems like you have another distribution of python on your path: take a look in your PATH environment variable.  

You can override the above behaviour by setting *XLOIL_PYTHON_VERSION* to "3.11" in your `%APPDATA%\xlOil\xlOil.ini`.  However you may still encounter unexpected behaviour if you have conflicting python versions on path in the same environment.

**Comment by stefanomorni** [comment]
Thank you very much for your answer.
When you say "take a look at your PATH environment" you mean the "generic" Windows user and system environment or a path setting in the xloil.ini file?

This is my xloil.ini file:

#
######## xlOil Settings #########
#
# This is a TOML file.
#
#################################
#
[Addin]

##### Plugins to load
#
# Load these plugins. The directory containing xloil.dll is searched
# first, then the normal DLL search path order.
#
Plugins=["xlOil_Python", "xlOil_SQL", "xlOil_Utils"]

#
# Load any plugins in the same directory as the core dll which 
# match this pattern.
#
# PluginSearchPattern="xloil_*.dll"


##### Log file settings 
#
# Intensity of logging, choose from:
# "trace", "debug", "info", "warning", "error", "critical", "off"
#
LogLevel="warning"

#
# Level at which xlOil will pop up a log window to display recent 
# log entries
#
LogPopupLevel="error"

#
# The log file is created at <name-of-ini-file>.log and in the same 
# directory unless specified below
#
#LogFile="my.log"

#
# Log file rotation is controlled by these two parameters. A single
# log file can grow to the *LogMaxSize* in Kb. Once this limit is
# reached, a new blank log file is started, existing old log files
# are renamed and the oldest is deleted to ensure maximum of 
# *LogNumberOfFiles* files.
# 
#LogMaxSize="512"
#LogNumberOfFiles="2"

#
# Enable this to help diagnose problems with loading xlOil.dll
# from the xll loader
# 
# StartupTrace=true

# If you have an ini file at %APPDATA%\xlOil\xlOil.ini, the core xlOil.dll
# is loaded using those settings before any other xlOil-based XLL. Since only one 
# instance of xlOil can be hosted in Excel, one settings file must take precedence. 
# The assumption is that if you have xlOil installed, you want those settings to 
# be the primary ones.  The below option, when used in a XLL-specific ini file,
# allows it to be loaded before the core.
# LoadBeforeCore="False"

##### Date
#
# The date formats xlOil will attempt to parse for a string to date
# conversion. Syntax follows C++ get_time here: 
# https://en.cppreference.com/w/cpp/io/manip/get_time
# Note the date parsing is case sensitive because get_time is case 
# sensitive on Windows.
#
DateFormats=["%Y-%m-%d", "%Y%b%d", "%d.%m.%Y"]

# 
# The key XLOIL_PATH is edited by the xlOil_Install powershell script
# Note: Use [[]] syntax because the order of Environment variables matters
#
[[Addin.Environment]]
XLOIL_PATH='''D:\Cloud\OneDrive\PortableApps\mambaforge\envs\xlpy\share\xloil'''
[[Addin.Environment]]
PATH='''%PATH%;%XLOIL_PATH%'''


##### Python Plugin Settings
#
[xlOil_Python]
#
# Python modules to load on start up. Must be on python's sys.path.
# xlOil provides the following optional modules:
#   * xloil.xloil_ribbon: adds a ribbon toolbar with some useful functions
#   * xloil.jupyter: adds jupyter interaction
#
LoadModules=["xloil.xloil_ribbon","xloil.jupyter","xloil.pandas","xlpyFunctions", "xlpyProcedures"]

#
# On workbook open, look for a python file matching this template 
# where * is replaced by the Excel workbook name
#
WorkbookModule="*.py"

#
# Look for a module matching this pattern in the directory of the 
# XLL when it is loaded where '*' is replaced with the addin name.
# The default is "*.py" which means an ini file is optional for a 
# simple addin
#
#AddinModule="*.py"

#
# Calls Py_SetPath before initialising python. This allows explict
# specification of python's sys.path rather than using the usual
# search routine, which overrides any setting of PYTHONPATH.
# Generally this option is not required.
#
#SetSysPath='''.'''

#
# Sets the library for COM support. This is used by the `xloil.app` 
# and `to_com` functions although can be override on a per-call basis.
# The default is 'win32com', 'comtypes' is also available. 
#
#ComLib="comtypes"


#
# Selects the debugger to use. The choices are:
#   * Visual Studio 2019+ : no need to pre-select this, just attach to 
#     a running Excel process
#   * VS Code: choose `vscode` or `debugpy`. The `DebugPyPort` attribute
#     then determines the port on which the server listens.
#   * Pdb: choose 'pdb'
#
Debugger = "vscode"

#
# Determines the port on which the server listens.
# 
DebugPyPort = "5678"

##### Python Environment
#
# We need to set the python environment paths. Usually this is done automatically 
# by `xloil install` or `xloil create` or the ribbon.
#
# Usually just set PYTHONEXECUTABLE - python should be able to figure out the rest.
# xlOil also uses this variable to help detect the presence of a virtual Environment. 
# Alternatively set the PYTHONPATH, PYTHONHOME and PATH directly as required by your
# distribution.
#
# Note environment vars can be set by dynamically expanding a registry key.
#
[[xlOil_Python.Environment]]
	#
	# Tells python to do case-insensitve module name lookup and so minimises 
	# surprises on windows when creating workbook and addin modules. Recommended!
	#
    PYTHONCASEOK="1"

	#
	# If this environment variable is set, xlOil tries to load the corresponding
	# pythonXY.dll as the interpreter. If unset or blank, xlOil uses the first python 
	# version discovered using the paths set below.
	# 
	XLOIL_PYTHON_VERSION=""

	#
	# Additional paths to add to python's sys.path. Prefer to add user search
	# paths here and reserve the PYTHONPATH setting below for system paths. 
	# (We make the empty value a semi-colon so that the variable exists 
	# for the environment variable expansion below)
	XLOIL_PYTHON_PATH="D:\\Cloud\\Code\\xlOil\\Modules"

[[xlOil_Python.Environment]]
	
	#
	# PYTHONEXECUTABLE should point to the python.exe of the current environment.
	# Note it is possible to dynamically expand registry keys contained in angle 
	# brackets <>.
	#
	PYTHONEXECUTABLE='''D:\Cloud\OneDrive\PortableApps\mambaforge\envs\xlpy\python.exe'''
	
	PYTHONPATH='''%PYTHONPATH%;%XLOIL_PYTHON_PATH%'''
	

I noticed, that if I edit the setting:

[[Addin.Environment]]
PATH='''%PATH%;%XLOIL_PATH%'''  to 
PATH='''%XLOIL_PATH%''' (removing the %PATH%)

xlOil loads fine.

Is this a "cleaner" solution then setting XLOIL_PYTHON_VERSION to "3.11" or my also close problems down-the-line?

I have several copies of python3.dll in the system, but only one in the mamba environment xlpy set in xloil.ini. Here is the list:

D:\Cloud\OneDrive\PortableApps\mambaforge\pkgs\python-3.11.3-h2628c8c_0_cpython\python3.dll
D:\Cloud\OneDrive\PortableApps\mambaforge\envs\xlpy\python3.dll
D:\Cloud\OneDrive\PortableApps\mambaforge\pkgs\python-3.11.2-h2628c8c_0_cpython\python3.dll
C:\Program Files\Calibre2\app\bin\python3.dll
D:\Cloud\OneDrive\PortableApps\mambaforge\pkgs\python-3.10.8-h4de0772_0_cpython\python3.dll
D:\Cloud\OneDrive\PortableApps\Anaconda\pkgs\python-3.10.6-hbb2ffb3_0\python3.dll
D:\Cloud\OneDrive\PortableApps\mambaforge\pkgs\python-3.10.6-hcf16a7b_0_cpython\python3.dll
D:\Cloud\OneDrive\PortableApps\mambaforge\python3.dll
D:\Cloud\OneDrive\PortableApps\Anaconda\python3.dll
D:\Cloud\OneDrive\PortableApps\Anaconda\pkgs\python-3.10.5-hcf16a7b_0_cpython\python3.dll
D:\Cloud\OneDrive\PortableApps\Anaconda\envs\smo\python3.dll
D:\Cloud\OneDrive\PortableApps\Anaconda\pkgs\python-3.9.12-h6244533_0\python3.dll
D:\Cloud\OneDrive\PortableApps\Anaconda\pkgs\python-3.8.13-h9a09f29_0_cpython\python3.dll
D:\Cloud\OneDrive\PortableApps\Anaconda\pkgs\python-3.8.13-hcf16a7b_0_cpython\python3.dll
D:\Cloud\OneDrive\PortableApps\Uniconverter\Data\local\meta\@PROGRAMFILES@\Wondershare\UniConverter 13\DownloadRes\python3.dll.__meta__
D:\Cloud\OneDrive\PortableApps\Uniconverter\Data\local\modified\@PROGRAMFILES@\Wondershare\UniConverter 13\DownloadRes\python3.dll
D:\Cloud\OneDrive\PortableApps\WinPy64v3680\python-3.6.8.amd64\python3.dll
D:\Cloud\Code\Tutorials\PySide2\target\Chat Client\python3.dll
D:\Cloud\Code\Tutorials\FlaskSample\venv\Scripts\python3.dll
D:\Cloud\Code\Tutorials\PageSpider\venv\Scripts\python3.dll
D:\Cloud\Code\Tutorials\EssentialTraining\venv\Scripts\python3.dll
D:\Cloud\Code\Tutorials\MegaCourse\venv\Scripts\python3.dll

and here is the content of the xloil.log:

[2023-04-27 23:01:43.729] [logger] [error] [StubLoader.cpp:176] Failed LoadLibrary for: xlOil_Python310.pyd
[2023-04-27 23:01:43.783] [logger] [error] [PluginLoader.cpp:159] Plugin load failed for D:\Cloud\OneDrive\PortableApps\mambaforge\envs\xlpy\share\xloil\xlOil_Python.dll: Initialisation failed
Path=C:\Program Files\Microsoft Office\Root\Office16\;D:\Cloud\OneDrive\PortableApps\mambaforge;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows;C:\Windows\system32;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;D:\Cloud\OneDrive\PortableApps\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Sequentum\Sequentum Enterprise;C:\Users\Stefano\AppData\Local\Microsoft\WindowsApps;C:\Users\Stefano\AppData\Local\Programs\Microsoft VS Code\bin;D:\Cloud\OneDrive\PortableApps\Aria2c;D:\Cloud\OneDrive\PortableApps\Curl 763x64\bin;C:\Users\Stefano\.dotnet\tools;C:\Windows\SysWow64\;D:\Cloud\OneDrive\PortableApps\Poetry\bin;C:\Users\Stefano\.android\avd\Pixel_4a_API_30_And_11.0_Rooted_.avd;D:\Cloud\GoogleDrive\sdkTools;C:\Users\Stefano\.android\avd;C:\Users\Stefano\AppData\Local\Android\Sdk\emulator;;C:\Program Files\Microsoft Office\root\Client;D:\Cloud\OneDrive\PortableApps\mambaforge\envs\xlpy\share\xloil;D:\Cloud\OneDrive\PortableApps\mambaforge\envs\xlpy;D:\Cloud\OneDrive\PortableApps\mambaforge\envs\xlpy\Library\bin

I apologize for the long post and thank you in advance for your patience
... I hope i'm am not abusing of it.

Hope you can help me.

Thanks

**Comment by cunnane** [comment]
I mean the generic system/user PATH environment variable.

The reason that setting `PATH='''%XLOIL_PATH%""` in xlOil.ini works is because it clears the path environment variable when xlOil starts up (instead of appending to it).  If you don't need anything else on that path for any other addin in Excel, then this solution is perfectly fine.

The item on your path causing the conflict is probably `D:\Cloud\OneDrive\PortableApps\mambaforge`

**Comment by stefanomorni** [comment]
Thanks a lot.
I removed D:\Cloud\OneDrive\PortableApps\mambaforge and everything works fine.

Best regards
Stefano
👍

**Comment by cunnane** [comment]
Great!  Happy it worked out!
