### ISSUE TITLE
Cannot find reference 'Range' in __init__py

### ISSUE THREAD

**Issue by ShieldTrade** [cunnane/xloil#42]
I have this error.  I can see Range class in xloil\stubs\xloil_core\_init_.py. 
![Screenshot 2023-05-01 170830](https://user-images.githubusercontent.com/62026612/235476351-3f7b080f-c2b0-4d53-bd9d-cf2125e057a0.png)

**Comment by cunnane** [comment]
If you have multiple python versions it's possible your linter is running the wrong one but let me check this works as expected...

**Comment by cunnane** [comment]
This is fixed in v0.17.9 (just released)
