### ISSUE TITLE
Writing a pandas DataFrame to a range

### ISSUE THREAD

**Issue by talalvas** [cunnane/xloil#43]
Hello,
I'm new to your project. Very impressive.
I initially tried it to write a Asynchronous UDF (I'll post a question regarding this issue in the future) and stayed for more!

I'm writing an UDF that runs a query and saves the query results as a pandas Dataframe.
I want to write the df back to a specific range **without** the index column.
I find it extremally difficult to do.
The closest i get is this way:

```python
rng_test = xlo.Range('AM4:AZ6')
order_df = order_qry.get_res_dataframe()  # This function returns pandas df

# Two ways to write that doesn't do what I need:
rng_test.value = order_df  # Writes to the range the df with the unwanted index column
rng_test.value = order_df.values.tolist()  # Writes to the range the df without the index column, but the header row is missing
```

Can you help me to find a way to write the df results **without** the **index** column and **with** the **header** row?

Thanks!

**Comment by talalvas** [comment]
Hello again,
I was able to find a solution to this issue by setting the first column of the df as an index, and then write it to sheet.
```python
rng_test = xlo.Range('AM4:AZ6')
order_df = order_qry.get_res_dataframe()  # This function returns pandas df
order_df.set_index(order_df.columns[0], inplace=True)  # Set the first column as an index

rng_test.value = order_df  # Writes the df to range **without** the unwanted index column
```

You may want to consider in future version to improve the default convertors available with XLOIL.
You probably know about xlwings, they have a very convenient way to use convertors by 'Converters and Options' that enables you to use convertors while reading\writing from\to a range.

Thank you for your amazing work!

**Comment by cunnane** [comment]
Yes something like that would be faily straightforward to implement, but I'm not sure about the nicest syntax.  All the current converters (which can be used in worksheet functions) do is output a *numpy* array so the meantime something like the following should work
``` python
rng_test.value = np.vstack([order_df.columns.values,order_df.values])
```

**Comment by talalvas** [comment]
Thank you for your replay and for this library.
