### ISSUE TITLE
Return #N/A from a UDF

### ISSUE THREAD

**Issue by talalvas** [cunnane/xloil#47]
Hello,
I try to return the error `#N/A` as a UDF result. Similar to Excel's `=NA()` function.
How can I achieve this using xloil or win32com library?

the class `xloil.CellError(value: int)` seems to have this ability, but I'm not sure how to use it as a return `#N/A` value.
I've found out that `xlo.CellError(7)` returns `#DIV/0!`
And for `xlo.CellError(x) (x!=7)` it returns `#VALUE!`
But it doesn't seems to be by design.

```python
# Write result to sheet
    try:
        return filtered_df[ret_col_name].iloc[0]
    except KeyError:
        return xlo.CellError(7)  # Returns #DIV/0!
    except IndexError:
        return ???  # How to return #N/A
```

**Comment by cunnane** [comment]
Returning `xloil.CellError.NA` should do it

**Comment by talalvas** [comment]
The only thing I didn't tried... Thanks @cunnane !
