### ISSUE TITLE
debug issues

### ISSUE THREAD

**Issue by xloilamar** [cunnane/xloil#48]
HI,
I am trying to debug python code from Excel using xloil, but getting an error 
" [error] During Event Event_PyUserException: TypeError: _Handler_pdb_window.__init__() takes 1 positional argument but 4 were given" .

I am calling xlopydebug("pdb") from excel. and used "raise Exception("debug") " on python code.
can anyone please help, thanks a lot.

**Comment by cunnane** [comment]
I'll double check this later and make a patch but I think if you change the file `xloil/debug.py` in your python site packages like this:
```
   (from) 163: xloil.event.UserException += _Handler_pdb_window
   (to)   163: xloil.event.UserException += _Handler_pdb_window().call
```

It should do the trick

**Comment by cunnane** [comment]
I needed to change a couple more lines, but this should be working in v0.17.10 which I've just released.

**Comment by cunnane** [comment]
Closing, let me know if you're still seeing problems.
