### ISSUE TITLE
Using xlo.call on vba UDF

### ISSUE THREAD

**Issue by talalvas** [cunnane/xloil#50]
Hello,
I'm trying to use `xlo.call`on a function written with VBA in my workbook.

This function is under module named 'Priority' in my workbook VBA Project library
```vba
Public Function TestFunc()
    TestFunc = "Success"
End Function
```
When i try to call it from a cell i recive the expected output.
```excel
=TestFunc()  # Cell value is "Success"
```

When I try to call it from python I receive error message
```python
@xlo.func()
def xlo_call_test():
    x = xlo.call('TestFunc')
```
Returns error message:
`#Unrecognised function 'TestFunc'`

For all the standard worksheet functions `xlo.call` works properly.

What seems to be the issue?

**Comment by cunnane** [comment]
`xloil.call` is only for built-in functions, similar to what is available under `Application.WorksheetFunctions` but also including the very old Excel v4 macro functions.  

Use `xloil.run` to call user-defined functions - it invokes `Application.Run` so is single-threaded.
