### ISSUE TITLE
problem with 'xlo.Range' variable decleration

### ISSUE THREAD

**Issue by talalvas** [cunnane/xloil#51]
Hello,
I'm using a UDF that gets a range variable.

I declare the `sup_range` variable as an `xlo.Range` and the variable type i get in the function is `xloil_core._XllRange`.
The variable type i wish to receive is `xloil_core.Range` which is more convenient for me to work with.
So I must do the conversion as seen in the code below.

Is there a way to get the variable in `xloil_core.Range` directly without the need for conversion?

```python
@xlo.func
def xlo_rfq_sups_list(sup_range: xlo.Range, next_sup: int):

    # default var type
    print(f'{type(sup_range)}') # xloil_core._XllRange

    # convert 'xloil_core._XllRange' to 'xloil_core.Range'
    sup_range = xlo.Range(sup_range.address()) 
    print(f'{type(sup_range)}') # xloil_core.Range

```

**Comment by cunnane** [comment]
The reason xlOil does this by default is performance: the `XllRange` object is a thin wrapper around the object passed by Excel to xlOil, so nothing is copied.  Internally there is also a `ComRange` which goes via the usual VBA-style interfaces.  My idea was for them to have similar interfaces, up to the point where you start calling COM properties directly - what methods are you calling on the range?

Unfortunately it's not easy to write an `xloil.converter` to handle this case as the `Range` annotation is special, but it isn't too difficult for me to adapt the code to allow you to insist on receiving a COM range object.

**Comment by cunnane** [comment]
@talalvas Are you able to give an example of code which requires an `xloil_core.Range` object rather than a `xloil_core._XllRange` one?

**Comment by talalvas** [comment]
Hi @cunnane,
I know it doesn't sound too important, but just a quick example:

When using square brackets (`var[x, y]`) on the default `xloil_core._XllRange` variable type we will get `numpy.ndarray`,
but if we will use square brackets on `xloil_core.Range` variable we will get `str` type.

So, if you are using `var[x, y]` it makes more sense (and more convenient) that it will return the intersection of row `x` and column `y` (The behevior for `xloil_core.Range`),
rather than returning an array derived from this range (The behevior for `xloil_core._XllRange`).

I hope it makes sense to you.
Tal.

**Comment by cunnane** [comment]
In 0.17.11, I've fixed the behaviour of getitem in *_XllRange* to match the expected/documented behaviour for `xlo.Range`

**Comment by cunnane** [comment]
Closing this, let me know if you see any further inconsistencies
