### ISSUE TITLE
async macro writing to XLL

### ISSUE THREAD

**Issue by ShieldTrade** [cunnane/xloil#59]
I can do.

```
@ xlo.func(command=True)
def write_to_ws():
    xlo.worksheets['Sheet1']["A1"] = 'Oil'
```

I would like to do.     ( I.e Py macro which fetches data using `aiohttp `. When data are available print them to a range.)

```
@ xlo.func(command=True)
async def get_data_from_connection_then_write():
    await asyncio.sleep(3)   # simulating a connection which takes 3 sec to return data
    xlo.worksheets['Sheet1']["A1"] = 'Oil'
```

I did many experiments.  This is one of the most promising. 

```
@ xlo.func(command=True)
def get_data_from_connection_then_write():
    loop = xlo.get_event_loop()
    loop.run_until_complete(get_data())

async def get_data():
    await asyncio.sleep(1)
    xlo.worksheets['Sheet1']["A1"] = 'Oil'
    return
```

data are printed but then I get this

```
[2023-09-01 20:32:28.060] [logger] [error] [EventLoop.h:88] Failed to initialise python worker thread: RuntimeError: RuntimeError: This event loop is already running
Traceback (most recent call last):
  File "C:\shieldtrade\ave\venv\lib\site-packages\xloil\importer.py", line 94, in _pump_message_loop
    loop.run_until_complete(wait())
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 618, in run_until_complete
    self._check_running()
  File "C:\Users\lucio\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

[2023-09-01 20:32:28.061] [logger] [warning] [logging.py:17] sys:1: RuntimeWarning: coroutine '_pump_message_loop.<locals>.wait' was never awaited
```
XLL does not crashes and if I close the notepad I can call again `get_data_from_connection_then_write` and It works without any more error.

Is this just a warning message I can ignore or I am doing something wrong?
What would be the best practice to do it?

**Comment by cunnane** [comment]
xlOil owns and runs the event loop returned by `xloil.get_event_loop()`, so you shouldn't try to run it yourself.  You just need to schedule tasks on the loop which you can do with [`run_coroutine_threadsafe`](https://docs.python.org/3/library/asyncio-task.html#asyncio.run_coroutine_threadsafe).

Is there a reason not to use RTD functions here, are you trying to workaround the RTD throttle limits?

**Comment by ShieldTrade** [comment]
I can indeed use a RTD function for my needs, I am just practicing with xlOil and trying to improve my Py concurrency skills.

I understand xlOil lives in  a background thread and has its own event loop. 
It looks to me that no async function can write to xlOil in any case.

This might be due to my lack of python concurrency knowledge. I understand you are not here to teach python. Any help would be appreciated
```
@ xlo.func(command=True)
def get_data_from_connection_then_write():
    loop = xlo.get_event_loop()
    asyncio.run_coroutine_threadsafe(get_data(), loop)   
  # Submit the coroutine to . xloil loop


async def get_data():
    await asyncio.sleep(1)
    xlo.worksheets['Sheet1']["A1"] = 'Oil'
    return
```

**Comment by cunnane** [comment]
There's one last trick: any call to Excel's API, e.g. to write to the worksheet, must be done on the main thread or Excel is liable to crash.  You can achieve that with:
```
  async def get_data():
      await asyncio.sleep(1)
      def do_it():
          xlo.worksheets['RTD']["B2"] = 'Oil'
      await xlo.excel_callback(do_it)
```

**Comment by keithalewis** [comment]
This _is_ tricky. Excel has a message pump. Here is some code that parameterizes how much time you want to give it to catch up.
`#include <Windows.h>

// https://devblogs.microsoft.com/oldnewthing/2005/02/22
void DoEvents(int ms)
{
	MSG msg;
	while (PeekMessage(&msg, nullptr, 0, 0, PM_NOREMOVE)) {
		BOOL b = GetMessage(&msg, nullptr, 0, 0);
		if (b == -1) {
			MessageBoxA(0, "GetMessage returned -1", "Error", MB_OK);
			break;
		}
		else if (b > 0) {
			TranslateMessage(&msg);
			DispatchMessage(&msg);
		}
		else if (msg.message == WM_QUIT) {
#ifdef _DEBUG
			MessageBoxA(nullptr, "Calling PostQuitMessage", "Info", MB_OK);
#endif 
			PostQuitMessage(static_cast<int>(msg.wParam)); // exits when macro is done?
		}
	}
	Sleep(ms);
}`

**Comment by ShieldTrade** [comment]
@cunnane, @keithalewis , 
It looks like it does what I wanted to. 

xlOil confirms itself as an excellent library.
Tx for your help. I would like to sum it up and ask you a few more questions


```
# can be called as a XLL macro
# calculation mode can be Manual
# perform an async operation, like getting data from a connection or long calculation, and write the result to XLL

@ xlo.func(command=True)
def get_data_from_connection_then_write():
    loop = xlo.get_event_loop()
    asyncio.run_coroutine_threadsafe(get_data(), loop)   
    # Submit the coroutine to .xlOil loop. 
    #This function is meant to be called from a different OS thread than the one where the event loop is running.

 async def get_data():
      await asyncio.sleep(1)  # control is back to xlOil loop for 1 sec
      def do_it(): # xlOil loop is blocked 
          xlo.worksheets['RTD']["B2"] = 'Oil'  #  xlOil main thread can write XLL invoking a COM call. The writing cannot be awaited.  
      await xlo.excel_callback(do_it)  
      # schedule a callback to be run on main thread. 
      # When the writing is done the main thread tells its loop (xlOil loop) it can resume and run the next scheduled function 
```

If my comments of the code are true. `await xlo.excel_callback(do_it)` is the trick. The xlOil loop must be blocked to write to XLL, This is why the writing must be done by a Subroutines and not a Coroutines: using Subroutines we are also sure data values will be returned so that an awaitable call back function is possible. 
The awaitable call back function  kinds of  make the Subroutines itself awaitable. 

I think @keithalewis code can be used to measure the time it takes for` do_it()`  to execute and call back. During that time I suppose the GIL is locked.  I still have to figure out if `xlo.core_addin().async_throttle ` wich specify in milliseconds the time between runs of asyncio is ralated to the above time. 

if we change the code from ` asyncio.run_coroutine_threadsafe(get_data(), loop)`  to `loop.create_task(get_data())` the code works but it would not be threadsafe.  In the code below  `data `are not produced on the main xlOil thread. This is why 
we need threadsafe.

what do you think of my xlOil comment code and conclusion so far 

```
async def get_data():
      data  = await produce_data()  # data are not produced on the main thread
      def do_it(): 
          xlo.worksheets['RTD']["B2"] = data    
          await xlo.excel_callback(do_it)  
```

**Comment by cunnane** [comment]
There are two threads each with their own event loop:

1) xlOil's background thread with it's *asyncio* event loop
2) Excel's main thread with Excel's message queue (which interacts with the Win32 message loop)

It's generally unsafe to send a command to either one of these from another thread, so we need special thread-safe calls to schedule a command on the message loops, so that it eventually run on the correct thread.  Those commands are `run_coroutine_threadsafe` and `excel_callback`.  Each of these commands returns a `Future` which can be awaited on the *other* message loop.  Awaiting a future does not block the loop, it just pauses the function which called `await` - other tasks can continue to run on the loop.

A command in Excel is always called from the main thread (at least if it is called by Excel).  A COM action such as writing to the sheet must also be called on the main thread.

In terms of the GIL, xlOil needs to acquire it to check for and run tasks in it's message loop (1), but it then drops it to allow other threads to run.  Excel's main thread only has the GIL when it is running a python command.

**Comment by ShieldTrade** [comment]
Thank you. Short and clear explanation. As far as I am concerned this issue can be closed.
