### ISSUE TITLE
MsgBox

### ISSUE THREAD

**Issue by ShieldTrade** [cunnane/xloil#62]
I would like to display a MsgBox using xlOIl

In Excel VBA, I can use the MsgBox function

```
Sub MsgBox()
MsgBox "xlOil is a great lib"
End Sub
```

I read [MS win32Api](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox) and [pywin32-docs](http://timgolden.me.uk/pywin32-docs/win32gui__MessageBox_meth.html)

```
@ xlo.func(command=True)
def msg_box():
    xlo.app().MessageBox(0, "xlOil is a great lib")
    xlo.app().win32gui.MessageBox(0, "xlOil is a great lib")
```
are both giving me a module not found error

```
AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library._Application instance at 0x2345992157072>' object has no attribute 'MessageBox'

AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library._Application instance at 0x1712010462880>' object has no attribute 'win32gui'
```

is the [pywin32com library](http://timgolden.me.uk/pywin32-docs/html/com/win32com/HTML/docindex.html)  fully accessible

**Comment by cunnane** [comment]
The object you get from `xloil.app` is the *Excel.Application* object, but
*MessageBox* is part of the win32 api, but it just happens to be a first
class function in VBA.  Take a look at:
https://stackoverflow.com/questions/19160930/how-to-create-excel-or-windows-msg-box-using-com-in-python
