### ISSUE TITLE
UDFs is volatile, cell can not persist the value of calculation!

### ISSUE THREAD

**Issue by JohnnySG** [cunnane/xloil#64]
Dear Steven,

I have the following code that extract the number from string array:

```
import re
import numpy as np
import xloil as xlo


@xlo.converter(range=True)
def array_2d(x):
    if isinstance(x, xlo.Range):
        x = np.array(x.value, ndmin=2)
        x[x == None] = 0
    if isinstance(x, xlo.ExcelArray):
        x = np.atleast_2d(x.to_numpy())
    elif isinstance(x, xlo.SingleValue):
        x = np.array(x, ndmin=2)
    return x


num_pattern = re.compile(r"[+-]?\d*\.?\d+")


@xlo.func
def str2num(arr: array_2d, prefix=None):
    arr = arr.astype(str)

    if prefix is not None:
        pattern = re.compile(prefix)

    result = np.zeros_like(arr, dtype=float)

    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            string = arr[i, j]

            if prefix is None or pattern.search(string):
                match_num = num_pattern.search(string)
                if match_num:
                    result[i, j] = float(match_num.group())

    return result
```

It works correctly:
<img width="244" alt="1" src="https://github.com/cunnane/xloil/assets/9008521/4a120f9e-59fa-4419-869e-bd7056cc8272">

But if I reopen excel, cell can not persist the value of calculation until recalculation:
<img width="269" alt="2" src="https://github.com/cunnane/xloil/assets/9008521/0cc1550b-a5b8-4a30-822e-012487b4e793">

**Comment by cunnane** [comment]
Unfortunately, I can't replicate this.  If the cell shows `#NAME?` it doesn't mean that the UDF is volatile.  Possibly the sheet is being opened before xlOil has finished loading your modules?  Try opening a blank workbook first, then open the sheet containing your `str2num` function.

**Comment by JohnnySG** [comment]
Wow, thank you! It seems true that the sheet is being opened before xlOil has finished when I straightly open the sheet!

**Comment by cunnane** [comment]
I implemented the background load as a feature to avoid blocking the Excel UI, however, I can see it has unintended consequences!  I'll add an option to turn it off.

**Comment by cunnane** [comment]
I added this feature in xloil 0.18.3, the setting is *UseLoaderThread* in xloil.ini

**Comment by cunnane** [comment]
I added this feature in xloil 0.18.3, the setting is *UseLoaderThread* in xloil.ini
