### ISSUE TITLE
WorksheetFunction.TIMEVALUE

### ISSUE THREAD

**Issue by ShieldTrade** [cunnane/xloil#65]
`xloil.app().WorksheetFunction.TIMEVALUE("8/27/2023 20:00")`
or
`xloil.app().WorksheetFunction.TimeValue("8/27/2023 20:00")`  # vba name

I have this error no attribute error

AttributeError: AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library.WorksheetFunction instance at 0x2074068800656>' object has no attribute 'TIMEVALUE'

`xloil.app().WorksheetFunction.Sum(1, 3)` works correctly

**Comment by cunnane** [comment]
[WorksheetFunction](https://learn.microsoft.com/en-us/office/vba/api/excel.worksheetfunction) is part of Excel's COM API - the only methods available are listed in the link.  `TimeValue` is a first class function in VBA so is not available this way.  Also I'm not sure why you'd want to call it, I'm sure that there are better date-parsing libraries in python!

**Comment by ShieldTrade** [comment]
Thankyou.

[excel-functions](https://support.microsoft.com/en-au/office/excel-functions-by-category-5f91f4e9-7b42-46d2-9bd1-63f26a86c0eb) can or canNOT be part of Excel's COM API. 

Yes I can avoid using Timevalue. I was just practicing
