### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by pausti2** [cunnane/xloil#67]
Thank you for the excellent library. A couple of minor issues spotted that I think are actually problems with python 3.8, but worth mentioning in case helpful to new users of xlOil.

1. xlOil couldn't auto-detect the python version after I installed it from my anaconda environment. I had to manually enter it at XLOIL_PYTHON_VERSION
2. My python code makes various standard imports including numpy. When loading my library from xlOil, python 3.8 could not find the dlls for these libraries. I worked around it by adding the following lines at the top of my script before importing xloil:

import os
s_path = os.environ['HOMEPATH']
loc_path = s_path.replace('\\','/')
os.add_dll_directory('C:/' + loc_path + '/anaconda3/envs/env1.0/Library/bin')
#this is to fix a DLL location bug that appears to be prevalent in python 3.8

import xloil as xlo

**Comment by cunnane** [comment]
I think this is more likely to be related to conda envs, I'll try to replicate.

Could I just confirm you are using the latest (0.17.13) version of xlOil - there was an issue with version detection fixed in this release.

**Comment by pausti2** [comment]
My colleague and I have different versions of xloil. 

I have version 0.17.10. I had problem 1 (ini file did not find python version 3.8 automatically) but not problem 2.

My colleague has version 0.17.13. He had problem 2 (numpy and other package dlls not found). However I believe he did not have problem 1.

**Comment by cunnane** [comment]
I've added support for Anaconda envs in 0.18.0 (which is available on PyPI) - they should now activate properly, adding that *Library/bin* path which is not present in the standard python environment.  The need to enter XLOIL_PYTHON_VERSION should generally have been remove in 0.17.13.

**Comment by pausti2** [comment]
Thank you very much
