### ISSUE TITLE
Copy and paste or save with another name an XLL file with Py code associated

### ISSUE THREAD

**Issue by ShieldTrade** [cunnane/xloil#68]
I have `my_file.xlsm` and its python workbook module `my_file.py` associated correctly working

1) When copy and paste `my_file.xlsm`.  
`my_file -copy.xlsm` has workbook module `my_file.py` associated
I can see the registered python functions but when I try to call them I get the local function id 16281.... not found error because files names are different

> When an Excel workbook is opened, xlOil tries to load the module <workbook_name>.py 

if I copy and paste `my_file.py`.  `my_file -copy.py ` is now created. Reopening `my_file -copy.xlsm` I can see 2 python modules associated: `my_file.py `and `xl_oil71F26......py` .Therefore calling any function will result in a duplicate functions error
If I cancel the redundant `my_file.py ` it works as expected.

2) When saving with another name `my_file.xlsm`. while it is open to` my_file_renamed.xlsm.` 
A new python module `my_file_renamed.py` is created.  But now` my_file_renamed.xlsm` has 2 python modules associated: `my_file.py `and `my_file_renamed.py` which contains the same code. Therefore calling any function will result in a duplicate functions error.
If I cancel the redundant `my_file.py ` it works as expected.

When renaming `my_file.xlsm`.  while it is closed it behaves like in 2.

Is this behaviors normal?

**Comment by cunnane** [comment]
I've added to fix to 0.17.14 (just released) which makes this behave more as expected.

**Comment by ShieldTrade** [comment]
Thankyou. Now it works as expected

Is there a way I can see your changes?

**Comment by cunnane** [comment]
[This is the relevant commit](https://github.com/cunnane/xloil/commit/db6f5b89a17693a090de80aeec672f88be5443ff)
