### ISSUE TITLE
event.SheetChange does not seem to work

### ISSUE THREAD

**Issue by dutch-rob** [cunnane/xloil#70]
I tried to run a function that gets triggered by a change in a worksheet but I was not able to get it to work.
I am attaching some code where I tried. I also tried a few other events that I found in the examples of the documentation.
WorkbookNewSheet, AfterCalculate, and SheetBeforeDoubleClick appear to work as expected but not SheetChange

I am also attaching a debug/log file that logged 
- First opening a new workbook (with only an empty 'Sheet1') and closing it without doing anything in the workbook. That shows one 'firing' of AfterCalculate but that did not appear to trigger the function 'event_writeTimeToA1'
- The opening that workbook again: pressing 'del' which did trigger the 'event_writeTimeToA1' function; then typing in some text which triggered 'event_writeTimeToA1' again but the log does not mention firing SheetChange and the function 'what_changed' did not happen; the double clicked on some cell which shows up in the log and triggered 'sht_bef_dblclick'; then added a sheet which also appears in the log and triggered the right function.

(I also tried the SheetCalculate event , which also did not appear to work but didn't log that as above.)

Maybe you can point out what I am doing wrong. 
In the meantime I have the impression that some actions that should be able to trigger multiple events, only trigger AfterCalculate. E.g. each SheetChange event coincides an AfterCalculate event but in the log it appears that only AfterCalculate gets fired.

Best regards,
Rob

[xlOil_for_steven_cunnane.log](https://github.com/cunnane/xloil/files/12950397/xlOil_for_steven_cunnane.log)
[try_xloil_events.py.txt](https://github.com/cunnane/xloil/files/12950537/try_xloil_events.py.txt)

**Comment by cunnane** [comment]
Thanks for providing plenty of detail here, the even was not properly hooked up internally. It should be fixed in 0.18.0 which I've just released

**Comment by dutch-rob** [comment]
I just checked, and yes, it works now.
Thank you very much!! 👍🎈
