### ISSUE TITLE
UDFs with empty parameters crash excel

### ISSUE THREAD

**Issue by pausti2** [cunnane/xloil#73]
My setup is:
Anaconda 4.14.0
Python 3.8
xloil 0.18.0
numpy 1.20.3

Since upgrading xloil, calling a function that has no parameters from excel often crashes my spreadsheet

My functions look like this:

@xlo.func
def testcrash(x):
    return 1

@xlo.func
def testcrash2():
    return 1

@xlo.func
def testcrash3(x = 2):
    return 1

Only the second of these crashes excel. What's strange is I have had it working at times, and at other times it always crashes.

(It is worth mentioning that yesterday, xloil stopped working with "Importing the numpy C-extensions failed" errors. I don't know what caused it. To fix it I had to run pip install --force-reinstall numpy==1.20.3 and it was at this time I also upgraded xloil. So it is possible there is something wrong with my environment, but everything else works)

**Comment by cunnane** [comment]
I haven't been able to replicate this.  Is it still a problem in the latest xlOil (v0.18.2)?  Is it possible to try with a newer version of numpy or are you limited to that version?

**Comment by pausti2** [comment]
Thank you so much for looking at this. Unfortunately I am limited to my old version of numpy. However it is only a very minor issue so I will close this as it is working with latest libraries
Thanks again

**Comment by cunnane** [comment]
I have just fixed a random crash bug in 0.18.3, which plausibly could resolve this issue

**Comment by pausti2** [comment]
Thank you very much, this has fixed it
