### ISSUE TITLE
c++ assertion triggered

### ISSUE THREAD

**Issue by pausti2** [cunnane/xloil#74]
My setup is:
Anaconda 4.14.0
Python 3.8
xloil 0.18.0
numpy 1.20.3

The following function
@xlo.func
def testassertion(x):
    res = [[1,2,3],
           [1, 3, [1,2,5], 6]
           ]
    return res

Triggers a c++ assertion (see screenshot), which ultimately crashes the sheet, instead of throwing an exception

![Capture](https://github.com/cunnane/xloil/assets/25991246/6bac8177-ebe6-423a-9d4d-e330957124ea)

(for my personal use case, I call the function from vba using application.run, and it would be even better if it returned valid vba object rather than throw, but I appreciate that is likely breaking xloil design)

**Comment by andyvandy** [comment]
fwiw with 
* Python 3.11.4    (tags/v3.11.4:d2340ef, Jun  7 2023, 05:30:09) [MSC v.1934 32 bit (Intel)] on win32
* Numpy: 1.26.1
* xloil 0.17.13

I get `{1,2,3,#N/A;1,3,#VALUE!,6}` ( which seems like a reasonable output )

Can you try with a more recent version of Python and report back?

**Comment by cunnane** [comment]
I can replicate this and I have a fix which I'll release soon!

**Comment by pausti2** [comment]
@andyvandy unfortunately it's quite hard for me to try with a different python vn as I am working on a closed system
I think the result you demo'd must be what I was getting in my previous version of xloil as I have something that iterates through results of a similar function recursively in VBA and it was working before
@cunnane thank you vm for looking at it

**Comment by cunnane** [comment]
This is fixed in 0.18.1 which I just released

**Comment by pausti2** [comment]
Thank you
