### ISSUE TITLE
Numpy 1d array output conversion Error

### ISSUE THREAD

**Issue by andyvandy** [cunnane/xloil#75]
Hi Steven, hope all is well!

I've run into an issue with np array output conversion. I'm using 32 bit windows which feels likely related. (python 3.11)

```python
@xlo.func()
def repeat(input_num ):
    return np.array([in_val]*8)
```
in 32 bit excel this outputs: repeat( 4) - > {4;0;4;0;4;0;4;0}

```python
@xlo.func()
def repeat_simple_npy_type(input_num=43):
    return np.array([input_num,input_num], dtype=np.float64) #-> {43;0}
    return np.array([input_num,input_num], dtype=np.float32) #->{43;43}
    return np.array([input_num,input_num], dtype=np.float16) #->Unsupported numpy date type
    return np.array([input_num,input_num], dtype=np.longfloat) #->Unsupported numpy date type
    return np.array([input_num,input_num], dtype=np.uint32) #->{43;43}
    return np.array([input_num,input_num], dtype=np.longlong) #->{43;0}
    return np.array([input_num,input_num], dtype=np.uint16) #->{43;0}
    return np.array([input_num,input_num], dtype=np.uint64) #->{43;0}
```

I believe I've narrowed this  down to around this line in `XlFromArray1d` where the pointertype is set
https://github.com/cunnane/xloil/blob/ad72355c3c212723e600dd8191407abf13a2ccff/libs/xlOil_Python/TypeConversion/Numpy.cpp#L661C60-L661C60
```c++
auto elementPtr = (TDataType*)PyArray_BYTES(pyArr);
        for (auto j = 0; j < dims[0]; ++j, ++elementPtr)
          builder(j, 0).take(converter.toExcelObj(builder, elementPtr));
```
I'm not sure exactly what would be needed for bullet proof generic type handling but I think that using the numpy iterators could possibly be a decent out of the box solution https://numpy.org/doc/stable/reference/c-api/array.html#array-iterators 

Hopefully I've narrowed this down enough ( let me know if there's anything I can do to make issues more helpful in the future )

Again, really appreciate you putting the library out there!

<details>
  <summary>Additional tests </summary>

- repeat(POWER(2,31)) -> = {2147483648;0;2147483648;0;2147483648;0;2147483648;0}
- repeat(POWER(2,31)+1) -> ={2147483649;4.45014880909622E-308;2147483649;4.45014880909622E-308;2147483649;4.45014880909622E-308;2147483649;4.45014880909622E-308}

these variations work
```python
@xlo.func()
def repeat_square(input_num:float = 42):
    return np.array([[input_num,input_num],[input_num,input_num]])
@xlo.func()
def repeat_vert(input_num:float = 42):
    return np.array([[input_num],[input_num]])
@xlo.func()
def repeat_diagnostic(in_val:float = 42):
    return np.array([in_val,in_val,type(in_val)])
@xlo.func()
def repeat_list(in_val:float = 42):
    return [in_val,in_val]

```
</details>

**Comment by cunnane** [comment]
Thanks for the detailed reporting, I've fixed in this 0.18.1 (just released)
