### ISSUE TITLE
in_wizard() not working

### ISSUE THREAD

**Issue by pausti2** [cunnane/xloil#80]
I am using python xloil and have this user defined function

@xlo.func
def test_fn_wiz(test = 0):
    if xlo.in_wizard():
        return "hello"
    return "goodbye"

It always returns "goodbye" even when in the function wizard.

(The background is that I have a function that calls back to excel vba using xlo.run. The function crashes excel when one presses OK from the function wizard, so have been trying to detect when in the wizard)

Thank you very much (as always) for any thoughts

**Comment by cunnane** [comment]
How embarrassing!  Thanks for reporting, this is fixed in 0.18.3 (just released)

**Comment by pausti2** [comment]
Thank you, this is very helpful!
