### ISSUE TITLE
ExcelObjCache breaking after 256th value

### ISSUE THREAD

**Issue by andyvandy** [cunnane/xloil#81]
Hi Steven,

I've run into some issues with the excel cache filling up. After the first 256 caches, the values will repeat.  

* * * * *
### Examples
Sample Sheet ( Setting the formatting to display seconds and holding shift F9 for 30s should do the trick )
```
=NOW()
=xloRef(A1)
=xloVal(A2)
```

This can also be seen with list outputs, the generated values will sum to 456 rather than 600 
```
class dummy:
    def __init__(self,val):
        self.val = val

@xlo.func()
def list_of_stuff():
    count= 200
    return [dummy(1)]*count + [dummy(2)]*count

@xlo.func()
def check_a_thing(thing:dummy):
    return thing.val
```

* * * * *
### Suspected Cause

I've taken a stab below at diagnosing the issue.

in ` ExcelObj _add` , when there is a cache hit we call `CellCache add` and cast the `size_t` return value to a `uint8_t`

https://github.com/cunnane/xloil/blob/1199790cb5c42b24f431de33212bda3431185901/include/xloil/ObjectCache.h#L316-L320

https://github.com/cunnane/xloil/blob/1199790cb5c42b24f431de33212bda3431185901/include/xloil/ObjectCache.h#L99-L109

However if `_objects` is larger than the max uint8 of 255 then we'll fetch a stale value. 

* * * * *

Changing the implementation to having a 4 character suffix could at least ensure that stale values aren't returned. 

My first instinct was to allow larger cache sizes but I could see that resulting in bloat for long running ticking applications.  

Trying to solve both the ticking use case as well as the list return use case may require implementing logic to be able to distinguish them.  

Interested to hear your thoughts on the matter. 

Again, thanks for making this project open source!

**Comment by cunnane** [comment]
It takes the address of the pointer to the cached object, then bit-packs it together with a calc id to get a cache id, which is very fast and always unique.  The id is a counter which increments every calc cycle, so we can tell which object is newer should two have the same address.   The caller information is stored with the cached object instead as part of the cache key.  A background thread removes outdated objects (same caller info, old calc id) which avoids the current overhead of cleaning the cache with each calc cycle.
