### ISSUE TITLE
Failed LoadLibrary for: xlOil_Python39.pyd

### ISSUE THREAD

**Issue by lukedays** [cunnane/xloil#9]
Hi! I was trying to assist a new user to install the library with no success.
- Fresh `xloil install`
- Using Anaconda with Python 3.10
- The following error occurs: `Failed LoadLibrary for: xlOil_Python39.pyd`
- Tried to include xlOilPythonVersion="3.10", but the error keeps happening

Any tips? Thanks in advance!

![image](https://user-images.githubusercontent.com/386899/187215795-f220bdd8-3097-4413-8ecb-4ca9f2aa6301.png)

![image](https://user-images.githubusercontent.com/386899/187216233-4a94a8f7-5afe-42a5-8873-a3459c6f0024.png)

**Comment by lukedays** [comment]
I could reproduce in my end as well.
- Fresh Anaconda install
- When doing `xloil install` on the base (root) environment, it works (it uses Python 3.9 by default)
- When creating a new environment with Python 3.10 and doing `xloil install`, the error above also occurs.

**Comment by lukedays** [comment]
Yeah you're right:
- base env: (python 3.9)
![image](https://user-images.githubusercontent.com/386899/187237837-1bdcf9be-aa9f-4983-9a11-342a4b437db7.png)
- different version env:
![image](https://user-images.githubusercontent.com/386899/187238028-fc72958d-aba4-4661-a67f-6bb83bc33059.png)

**Comment by cunnane** [comment]
I guess this is how anaconda envs are supposed to work?  Easiest fix I can see is for me to restore the functionality of the python version setting in the ini - which I previously took out to make things simpler!  I'll introduce it as an optional override in case the Py_Version approach isn't working as desired.

**Comment by lukedays** [comment]
Found a solution! Just run: 

`conda activate testenv`

Maybe we can include this in the docs for future users?

That's why I prefer pyenv...

**Comment by cunnane** [comment]
Great!  I've never been entirely clear what conda activate does!  I'm going
to include the version override setting as well as it's not terribly
convenient to have to launch Excel from a command prompt / batch script.

**Comment by lukedays** [comment]
Since running `conda activate` solves the issue, I'm closing it.
