### ISSUE TITLE
How to call a macro from a button and pass arguments

### ISSUE THREAD

**Issue by zssng** [cunnane/xloil#93]
excel auto rename the expression 'func arg1,arg2'(ok to call vba macro) to "workbook.xlsx!'func arg1,arg2'" and actually func registeredd in xll global. so the function not working

**Comment by cunnane** [comment]
You can't assign a global function to a button, Excel doesn't allow this (as far as I know!)  You need to create a workbook level macro which calls your function.   You can do this in VBA (with Application.Run) or using xlOil's local functions (i.e. a py file which accompanies the workbook).

**Comment by govert** [comment]
Ah - I suppose the question is about passing arguments in the button macro property - that indeed seems impossible.

**Comment by ShieldTrade** [comment]
Using the caption property of a button might help you.

```
""" Call a macro from a button and multiply by 2 its argument """""

Python
@xlo.func(command=True)
  def oil_multiply_by_2(num):
  var = num *2     # or call a function depending on num 
  ........

VBA
Private Sub CmdBtn_XllMultiplyBy2_Click()
    Call oil_multiply_by_2(CmdBtn_XllMultiplyBy2.Caption)
End Sub
```

CmdBtn_XllMultiplyBy2.Caption is what you write in the button and you can access it in the button properties ( right click the button). It will be passed to the xloil function as argument ( num )

**Comment by zssng** [comment]
My current approach is to dynamically create a function without parameters. The function's purpose is to call the target function with parameters. The downside is that it needs to be re-registered every time the workbook is reopened. Additionally, I've encountered another issue: when I bind this dynamic function name to a button, if I select and copy the range containing this button, Excel crashes directly. However, it functions normally after unbinding the function.

**Comment by keithalewis** [comment]
One possibility might be to use defined names for the parameters. The macro can evaluate the defined names to get the values.   
As for Excel crashing when you move the button, are you using the old controls or the ActiveX controls? The ActiveX controls don't seem to be well supported in current versions of Excel.

**Comment by cunnane** [comment]
If you run `xlo.Caller().address()` from the button macro you should get "[Book1]Sheet1Button1" (yes it could do with a separator, I'll add that now...).  You could look this string up in a dict of functions which you populate instead of doing the dynamic registration.

I'll look into why the dynamic registration approach doesn't work.

**Comment by zssng** [comment]
> 一种可能是使用参数的定义名称。该宏可以评估定义的名称来获取值。 至于移动按钮时Excel崩溃，您使用的是旧控件还是ActiveX控件？当前版本的 Excel 似乎没有很好地支持 ActiveX 控件。

只是旧的控件

**Comment by zssng** [comment]
> If you run `xlo.Caller().address()` from the button macro you should get "[Book1]Sheet1Button1" (yes it could do with a separator, I'll add that now...). You could look this string up in a dict of functions which you populate instead of doing the dynamic registration.
> 
> I'll look into why the dynamic registration approach doesn't work.

If a button is bound to a function instead of a command, the button can work, but copying, cutting, and other operations will cause Excel to crash and exit. Can Xloil dynamically register a command? Using xloil.register_functions can only register one function.

**Comment by keithalewis** [comment]
您只能将macro配给按钮

**Comment by zssng** [comment]
> 您只能将macro配给按钮

Yes, I tried to dynamically create a command using the following code. Copying the range where the button is located no longer crashes, but clicking the button still exits the program.

```
  func = xlo.func(
  fn=dynamic_registered_func,
  name=fn_new_name,
  command=True,
  register=False,
  local=False)
  xlo.register_functions([func], sys.modules[__name__])
```

**Comment by keithalewis** [comment]
I am going to have to defer to @cunnane on this. I only know the ancient C API.   
If `dynamic_registered_func` is a function with arguments, then registering as a macro (`command=True`?) would foul the argument stack.

**Comment by zssng** [comment]
`dynamic_registered_func` is a function without arguments

**Comment by zssng** [comment]
I solved this issue by executing specific actions based on the name of the button.
