### ISSUE TITLE
xloil.call problem

### ISSUE THREAD

**Issue by zssng** [cunnane/xloil#96]
There are two issues: 
1. the return value of the `offset` function is incorrect
2. some of the latest functions are not supported,eg: #Unrecognised function 'CHOOSEROWS'

**Comment by cunnane** [comment]
The `xloil.call` function allows you to invoke parts of the old Excel C API, it should probably come with a health warning as these functions are similarly named but may not behave identically to their [WorksheetFunction](https://learn.microsoft.com/en-us/office/vba/api/excel.worksheetfunction) counterparts.  In this case `xloil.call("offset",...)` returns a Range, so you need to pass it's *value* property back to the the worksheet.

The recently added batch of functions, LAMBDA, CHOOSEROWS, NORM.DIST, etc. cannot be called via any of Excel's APIs.  [Here's a workaround](https://stackoverflow.com/questions/75408782/is-worksheetfunction-for-new-excel-functions-chooserow-choosecols-accessible-i), however I'm not sure why you'd need to call any of Excel's worksheet functions from python as python usually has better / faster / simpler alternatives available natively.  In the case of CHOOSEROWS, Excel arrays are converted to *numpy* arrays by xlOil, so you can select specified rows with for example `arr[[1, 4, 8], :]`
