### ISSUE TITLE
Triggering async UDF from clicking a button

### ISSUE THREAD

**Issue by sskye123** [cunnane/xloil#98]
Hi, I am exploring this wonderful project and face a small problem. I can run async UDF in Excel by clicking 'Enter' button on the keyboard as a formula. But I want to link the async UDF with a button and trigger the async function by clicking it. I have tried xlo.run and xlo.call method by declaring the async UDF as macro=True or command=True but no luck. Could somebody help? Thank you.

**Comment by sskye123** [comment]
Actually, it can be done by following https://github.com/cunnane/xloil/issues/59. The issue can be closed. Thank you.

**Comment by cunnane** [comment]
Sorry, I was going to suggest this but didn't get around to checking it!  Glad you found it!
